name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'app1.py'
      - 'windows-build-requirements.txt'
      - '.github/workflows/windows-exe.yml'

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r windows-build-requirements.txt
          pip install pyinstaller

      # Optional: Tesseract is runtime-only; don't fail build if PATH isn't refreshed
      - name: Install Tesseract OCR (best-effort)
        shell: pwsh
        run: |
          choco install -y tesseract --no-progress
          $tessExe = 'C:\Program Files\Tesseract-OCR\tesseract.exe'
          if (Test-Path $tessExe) {
            & "$tessExe" --version
          } else {
            Write-Host "Tesseract installed but not in PATH yet; continuing build."
          }

      # Main build step: collect-all streamlit (code + data + metadata) to avoid metadata errors
      - name: Build EXE with PyInstaller
        run: pyinstaller --noconfirm app1.py --name EvidenceSynthesisApp --windowed --collect-all streamlit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: EvidenceSynthesisApp-windows
          path: dist/EvidenceSynthesisApp/**
